title: <style = color:'blue'> Caitlin Hansen
logo: "/images/headshot_hansen.png?raw=true" 
description: 
  <h1> exploring the world with data </h1>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
